version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '3306:3306'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  btsearch:
    build: .
    volumes:
      - .:/var/app
    entrypoint: ./docker-entrypoint.sh
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    depends_on:
      - db